### ISSUE TITLE
Links in the general features slide not readable

### ISSUE THREAD

**Issue by wenzeslaus** [veroandreo/grass-gis-talks#18]
In the `#GRASS generalities` slide, links are not readable due to the color of the background. I like the grass at the bottom. It could be lower to take less of the slide, more like https://wenzeslaus.github.io/dissertation-presentation/#/13 although that's perhaps too subtle. However, there still might be overlap. So, if you want to keep the colors and not worry about the overlap, you can help readability by including glow  (at the cost of design purity).

```css
.glow {
    text-shadow: 0 0 20px white, 0 0 18px white, 0 0 16px white, 0 0 14px white, 0 0 12px white, 0 0 10px white, 0 0 8px white, 0 0 6px white;
}
```

Use as `class="glow"`, e.g.,:

```html
<p class="glow">
...
</p>
```
